#!/bin/sh

case "$1" in
    start) exec /bin/udevadm --daemon ;;
    stop) /bin/udevadm control -e; exit 0 ;;
    settle) exec /bin/udevadm settle ;;
    trigger) exec /bin/udevadm trigger --action=add ;;
esac

echo "unknown action: $1"
exit 1
